version: '3.9'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: milinho123456
        MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo_data:/data/db